version: 1
disable_existing_loggers: False

handlers:
  events:
    class: logging.handlers.RotatingFileHandler
    filename: logs/current_run/events.jsonl
    maxBytes: 5_000_000
    backupCount: 5

  # This 'warnings' handler was likely missing. Add it back.
  warnings:
    class: logging.handlers.RotatingFileHandler
    filename: logs/current_run/warnings.jsonl
    maxBytes: 2_000_000
    backupCount: 3
    level: WARNING

  errors:
    class: logging.handlers.RotatingFileHandler
    filename: logs/current_run/errors.jsonl
    maxBytes: 2_000_000
    backupCount: 3
    level: ERROR

loggers:
  "unlearning_simulations":
    level: INFO
    # This list requires 'events', 'warnings', and 'errors' to be defined above.
    handlers: [events, warnings, errors]
    propagate: False

root:
  level: WARNING
  handlers: [warnings, errors]